---
- name: Show credentials from vault
  hosts: all
  connection: local
  gather_facts: false

  vars:
    - ansible_user: "{{ lookup('env','USERNAME') }}"
    - ansible_password: "{{ lookup('env','PASSWORD') }}"

  tasks:
    - name: Display Username from Vault
      debug:
        msg: "{{ ansible_user }}"
        
    - name: Display Password from Vault
      debug:
        msg: "{{ ansible_password }}"
